### ISSUE TITLE
Do stack and static/read-only memory stats belong here?

### ISSUE THREAD

**Issue by aartaka** [Shinmera/machine-state#7]
Hi! Thanks for linking to your library on Reddit! Does adding stack and static memory stats make sense for this library? I have the code I'm ready to contribute, but I'm not sure if it belongs here.

**Comment by Shinmera** [comment]
Not sure either. Though I'm also unsure about the usefulness of those metrics in general?

**Comment by aartaka** [comment]
> Though I'm also unsure about the usefulness of those metrics in general?

Indeed, the use-cases are quite narrow. The only one I can think of is recursion debugging. But I'm mostly chasing implementation coverage completeness here, so I'm interested in more metrics anyway :sweat_smile:

**Comment by Shinmera** [comment]
Well, I guess, what's a couple functions between friends. Sure, PR away.
